name: Check for New Tenders

on:
  workflow_dispatch:
  schedule:
    # Runs every 5 minutes (UTC time) for testing
    - cron: '0 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "python-telegram-bot==13.15" selenium webdriver-manager

      - name: Run the tender scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python tender_bot.py

      - name: Commit and push if files changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sent_tenders.json
          git diff --quiet --cached || git commit -m "Update sent tenders list"
          git push
